### ISSUE TITLE
Netflix blocked on digital ocean

### ISSUE THREAD

**Issue by Ryanthegiantlion** [ab77/netflix-proxy#105]
I am getting a new streaming error on netflix: "You seem to be using an unblocker or proxy"

I have added "nflxvideo.net" to my list of hosts and confirmed that on my machine both "netflix.com" and "nflxvideo.net" resolve to the dns proxy.

**Comment by Ryanthegiantlion** [comment]
Getting this area even when using 'zone "."' so I am think that perhaps the account is flagged or digital ocean has been flagged.

**Comment by freman** [comment]
Yeh same, tried 3 data centers now.

**Comment by ab77** [comment]
I think it is the later - my DO server stopped working. Best bet is to find another service, maybe try Vultr..

**Comment by notblocked** [comment]
DO is also not working for me as of today, but I suspect things are a bit more complicated than IP blocking (tried Vultr - same issue).

To understand what was happening, I added `zone "."` and tracked the connections from my roku 3 while Netflix was launching and then when starting the stream.

All DNS requests are forwarded to the instance (I have a router setup that will NAT port 53 requests to any destination to the instance) and as expected all connections to port 80/443 were to the instance, right until the stream started to buffer.

At that point, the roku created 4 direct connections to the xxxx.nflxvideo.net server's IP on port 80 (i.e. bypassing the proxy). The server clearly detected that the connection was from outside the US and thus the proxy/unblocker error message.

So it would seem that they are performing a more sophisticated detection, perhaps something along the lines of:
- resolve IP for xxx.nflxvideo.net via DNS
- send HTTP/S request to that IP, requesting the server IP
- media server returns it's actual IP
- roku connects to that IP

There are many relatively simple ways they could do this since they control the app on the Roku. Perhaps I'm mistaken and something leaked, but I can't see how. A VPN would work around these issues, but finding a non-blocked exit point is becoming increasingly difficult.

For reference, using VPN (PPTP / OpenVPN) on DO has been blocked for me for quite a while, despite proxying from DO working.

**Comment by envoys** [comment]
@notblocked that's weird, VPN on DO was not working but proxying on DO was working? That doesn't make sense. They have to have a way to determine if using a VPN but I am not sure how they are doing it.

FYI my DO is doing the same thing with the proxy, blocked now no matter what device or browser.

**Comment by ab77** [comment]
As far as I can see from my testing here, there are two conditions that must be met:

* client ipaddr talking to netflix.com must be geo-white listed (now covers both IPv4 and IPv6 protocols) otherwise the client will see `Error Code: M7111-1331-5059`
* client ipaddr talking to nflxvideo.net must match the ipaddr talking to netflix.com (within the same session) otherwise the client will see the error code `Error Code: M7031-1111`.

-- ab1

**Comment by envoys** [comment]
@ab77 so it would appear DO is blocked now as I am seeing 

> Error Code: M7111-1331-5059

**Comment by ab77** [comment]
IPv6 blocked indeed.

**Comment by envoys** [comment]
Now to find a lesser known VPS and use that...any suggestions? PM me :)

**Comment by ab77** [comment]
Sure :grimacing:

**Comment by Ryanthegiantlion** [comment]
@ab77 I think that second condition is only required sporadically. Streaming is working for me when using a different hosting provider without adding nflxvideo.net to the domain list.

**Comment by kyle95wm** [comment]
Well in this case I'll be destroying my droplet to free up my bill for other things. It was fun while it lasted. Would you guys suggest going with a service like Getflix which pretty much offers what we're doing here? only difference is they manage the backend. What we did was manage our own backends and updated whatever neeeded to be updated.

**Comment by envoys** [comment]
@kyle95wm i have heard sporadic reports getflix is down as well. But yes, it would be a wise idea to go with someone like that because they will always get around this :)

**Comment by WeirdG** [comment]
I'll try Unlocator when I get home tonight.  Their beta DNS was working yesterday.

**Comment by ab77** [comment]
New work around in place, make sure to read the README very carefully before redeploying, because the instructions are a bit more complicated now..

-- ab1
