### ISSUE TITLE
Netflix just invented new strategy

### ISSUE THREAD

**Issue by maxima120** [ab77/netflix-proxy#125]
the proxy stopped to work today. My first thought was - Netflix discovered my little known US VPS hosting and cut it off.. Then I switched to the UK one (I use to watch Better Call Saul).. And it was cut off as well. While I used UK proxy a week ago, the US I use every day and it was working yesterday OK.

So it seems its unprobable that they found out both of my proxies (both are obscure and small and were working for months) at about the same time..

Could you please have a look and see if Netflix changed the way to identify geolocations?

Another note which might help - the Xbox One Netflix app reports the usual - you are using proxy bla bla.. But when I switched to my smart TV (Sony) and tried the Sony Netflix app, it was saying that I am not connected to the internet (at the point when I click Play (request a video), opening and getting the Netflix lists are fine)..

**Comment by mikecurry74** [comment]
It is very probable that there are many people using the same VPS host you are using for the exact same reason and appeared on the Netflix Radar. Another possibility is that they are in the process of adding known hosting providers IP ranges, and they just got yours.

My suspicion is that things haven't changed since they added Geo checking to the CDN. It is also my suspicion that they are completely automated at this point and can detect a certain amount of non-US residents using a US baed IP which flags it for further inspection.

Best bet is to find another VPS and continue on watching Sons of Anarchy.

**Comment by maxima120** [comment]
you missed my point, I believe that it is unlikely they found out 2 of my hostings which both are small and worked well for months and completely unrelated to each other in a span of 4 days...

do you use one? have you tried today? is it still working?

**Comment by ab77** [comment]
Are you still using IPv4, native IPv6 or tunnelled IPv6?

**Comment by maxima120** [comment]
ok. may be Ive missed something :) still using ipv4? yes I am .. I thought your docker is for ipv4 only :)

**Comment by ab77** [comment]
You are a few versions behind :grimacing: 

In this space, situation changes almost daily, I would suggest rebuilding using the current instructions on DO or Vultr.

Let me know how it goes..

**Comment by maxima120** [comment]
sorry I am not a networking engineer and am a windows creature.. DO.. vultr .. :) rings not bell :)

**Comment by ab77** [comment]
The [README](https://github.com/ab77/netflix-proxy/blob/master/README.md) is your friend in that case..

Please re-open if you get stuck.

Good luck!

**Comment by kalenjin** [comment]
New Droplet or new DO account?

Many thanx
