### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by inet45** [ab77/netflix-proxy#14]
Hi thanks for the great work

i have 2 scenarios:

1- i setup the same on DigitalOcean VPS: i was able to access NetFlix

2- i setup this in on a VM at home to allow some friends to watch local content from another country, i set it up on Ubuntu 14.04LTS, all DNS names that are not in the  (sniproxy.conf  zones.override) files are resolving however anything in the (sniproxy.conf  zones.override) resolve to the server IP but no pages are displayed 

3- i have used my public IP in the configuration and used DMZ on my router to route all traffic to this VM

can you please advice

**Comment by ab77** [comment]
Hi there, in scenario (2), looks like your DNS resolution is working at least, if you are getting DNS responses with the IP of your local server. Next thing to check is the proxy listening on ports 80 and 443, on the box locally (i.e. telnet localhost 80; telnet localhost 443). Also check your iptables rules in case you are blocking incoming connections on ports 80 and 443. In fact, if you already have a firewall configured on your router, you can probably drop iptables on your server all together.

On your router, make sure you are forwarding ports 80/tcp, 53/udp and 443/tcp to your internal server IP.

You issue is likely due to the way the build script configured your server - you have iptables rules, which only allow traffic to your server from your external IP address, but you server is sitting behind NAT (your router). So start by dropping iptables and see where that takes you, then build up your rules as required..

-- ab1

**Comment by inet45** [comment]
Hi

thanks yes its IPTBALES issue, now i am able to access the site, login to the service without any error that my country is not supported, however still unable to play the video.

- i have used wireshark to capture traffic on a working pc in the supported location, and then listed all DNS query that happened in the packet capture, and i have included all these domains to the  (sniproxy.conf zones.override) 

- do you think i should do more or i missed something?

**Comment by ab77** [comment]
Try [enabling](https://github.com/dlundquist/sniproxy/blob/master/sniproxy.conf) logging in sniproxy and `tail -f /var/log/sniproxy.log` while you are doing stuff in the UI. It might shed some light on what's going on during video playback..

In theory, if you are able to browse the site, your proxy/DNS is working. What error are you actually getting when you try to playback video?

-- ab1

**Comment by inet45** [comment]
i should add the following:
error_log {
    # Log to the daemon syslog facility
    syslog daemon

    # Alternatively we could log to file
    #filename /var/log/sniproxy.log

    # Control the verbosity of the log
    priority notice
}

# Global access log for all listeners
access_log {
    # Same options as error_log
    filename /tmp/sniproxy-access.log
}


the error is (error 3222) its silverlight based player

**Comment by ab77** [comment]
Yep, add both and `tail` both logs in separate windows.

Also, SL 3222 is basically a connectivity error:
`3222: Connectivity issue in downloading media files, clear browser cache and try again.`

You may just have a Silverlight issue, although I am pretty sure Netflix have long switched to HTML5 based player, so not quite sure why you are still using SL. Just try it in Google Chrome browser to rule this out.

If not download/install [Fiddler2](http://www.telerik.com/download/fiddler/fiddler2) and point your browser[n1] through it, so you can see what requests are being made..

-- ab1

[n1] [ProxySwitchy](https://chrome.google.com/webstore/detail/proxy-switchysharp/dpplabbmogkhghncfbfdeeokoefdjegm?hl=en) is a good plugin for Chrome to do this quickly

**Comment by inet45** [comment]
i came across sites not displaying again!!

trying to telnet the vm on 80 or 443 but connection is not established
do you think the sniproxy is not working as it should?

**Comment by ab77** [comment]
Yeah, that's what it looks like. Try to figure out why sniproxy isn't starting/running and go from there..

**Comment by inet45** [comment]
will if i enable the logging 
it does not run, if i remove the logging it works!!

**Comment by ab77** [comment]
Are you building this from scratch using the original article or using build.sh script with Docker containers?

**Comment by inet45** [comment]
docker

**Comment by ab77** [comment]
Start again and paste the full output of `build.sh` at the end.
