### ISSUE TITLE
assign nexflix proxy listening to a single interface (eth0) ONLY

### ISSUE THREAD

**Issue by michaelri** [ab77/netflix-proxy#167]
hi ab77,

I got a virtual interface eth0:0 (another IP address).
would like to assign a service (tcp:443) to the eth0:0.

but netflix-proxy are listen to tcp:443 already, so won't work.
is there any way to force netflix-proxy listening to eth0 ONLY?

regards

mike

**Comment by ab77** [comment]
Hi Mike, what you are seeing is the Docker userland-proxy binding to all public IPs on the host in order to provide inbound connectivity to containers. You could read up on disabling it in the Docker docs, but keep in mind, that that will invalidate all of the custom iptables rules that are put in. You may be able to disable the proxy and add customise the rules to achieve what you want, but to be honest, it is probably just easier to run the additional service on another server and keep this one just to do the proxy job.

-- ab1

**Comment by kyle95wm** [comment]
I agree with that answer. It's usually best practice to have a single server for each role (example - web server is one server while a DNS server can be on another server). I mean, each server is only $5, and I'm paying to run 3 of those, so it's not too bad. Just thought I'd add my two cents in.
