### ISSUE TITLE
Setup without HE

### ISSUE THREAD

**Issue by knaeble** [ab77/netflix-proxy#173]
As far as I understand your project, using the HE tunnel is completely unneccessary if the VPS has a US IP adress. It would be nice to be able to build this without using the HE tunnel but native IPv6 as an alternative for those whose VPS-provider supports that.

**Comment by kyle95wm** [comment]
Even though some providers like DO support native IPV6, we choose not to use their IP space because as far as I'm aware, Netflix has blocked it. You CAN try to use native IPV6 with your provider if they support it. Just run the build script without any arguments and you should be fine. If you do run it with arguments, youll be expected to provide your HE username and password and index number if you have more than one tunnel on your HE account. Hope this helps.

**Comment by ab77** [comment]
The build script without any arguments on the IPv6 enabled host will assume a /124 subnet (x16 IPs) and divide it into two /125s (x8 IPs each), assigning the second subnet to the Docker bridge. It then uses manual NDP proxying to allow internal bridge to see the traffic, which it would not otherwise see. This is all a bit of a hack.

The proper way would be to have your provider to route a whole /64 prefix to the server. But even then, dividing a /64 into two /80s means RADVD won't forward packets to the internal Docker bridge and NDP proxying will be required. A /48 would be better.

**Comment by ab77** [comment]
Closing due to HE being permanently blocked.
