### ISSUE TITLE
You seem to be using an unblocker or proxy

### ISSUE THREAD

**Issue by jquiambao** [ab77/netflix-proxy#177]
Created a new droplet in DigitalOcean:
1. Selected One Click App
2. Selected Docker 1.11.1 on 14.04 
3. Ran:  `cd /opt && git clone https://github.com/ab77/netflix-proxy.git && cd netflix-proxy && ./build.sh`  everything returned **OK**
4. Logged in to portal and added my IP.
5. Went to DNS settings and added my droplet's IP.
6. Checked my IP in http://ipinfo.io/ and it shows my droplet's IP
7. Went to Netflix and got:
`You seem to be using an unblocker or proxy` **Error Code: S7111-1331-5059**

I tried NY and SF servers using the same steps but with no avail.

Am I missing something?

**Comment by kyle95wm** [comment]
Did you remember to specify your HE tunnel login details? Also don't enable native IPV6 on DO

**Comment by jquiambao** [comment]
Yup, I enabled IPV6 manually while creating the droplet.
When I ran the build.sh command it gave me an admin password which I used to login:
http://xxx.xxx.xxx.xxx:8080/login

Then I authorized my IP.

**Comment by kyle95wm** [comment]
nono heres what I did:

-create HE tunnel in whatever location
-create droplet (DO NOT ENABLE IPV6)
-on droplet console put: git clone https://github.com/ab77/netflix-proxy /opt/netflix-proxy && cd /opt/netflix-proxy && ./build.sh -u <tunnelbroker-username> -p <tunnelbroker-password>,

Basically after all of this is done, an IPV6 interface will be set up. DO's address space is blocked.

**Comment by jquiambao** [comment]
Ah somehow I misread what you last said about IPV6.  Anyway, I tried what you said and got this:

* enabling DNS recursion...                                                                                                     [ OK ] 
 * authorising clientip=182.18.228.195 on iface=eth0...                                                                          [ OK ] 
 * adding IPv4 iptables rules...                                                                                                 [ OK ] 
 * creating Docker and sniproxy configuration templates...                                                                       [ OK ] 
 * checking IPv6 connectivity...                                                                                                 [fail] 
 * configuring sniproxy and Docker...                                                                                            [ OK ] 
 * installing iptables|netfilter-persistent service...                                                                           [ OK ] 
 * socialising Docker with iptables-persistent service...                                                                        [ OK ] 
 * updating iptables-persistent init script...                                                                                   [ OK ] 
 * saving iptables rules...                                                                                                      [ OK ] 
 * creating zones.override from template...                                                                                      [ OK ] 
 * updating db.override with extip=192.241.169.54 and date=20160528...                                                           [ OK ] 
 * installing python-pip and docker-compose...                                                                                   [ OK ] 
 * configuring netflix-proxy-admin backend...                                                                                           [ OK ] 
 * configuring netflix-proxy-admin reverse-proxy...                                                                                     [ OK ] 
 * creating and starting Docker containers...                                                                                           [ OK ] 
 * configuring upstart...                                                                                                               [ OK ] 
 * reloading ipables rules...                                                                                                           [ OK ] 
 * no specific steps to execute for Ubuntu at this time...                                                                              [ OK ] 
 * testing DNS...                                                                                                                       [ OK ] 
 * testing proxy (OpenSSL)...                                                                                                           [ OK ] 
 * testing proxy (cURL)...                                                                                                              [ OK ] 
 * testing netflix-proxy admin site...                                                                                                  [ OK ] 

netflix-proxy-admin site=http://xxx.xxx.xxx.xxx:8080/ credentials=admin:passsord
WARNING: IPv6=Disabled
caching-resolver=Disabled
Hulu region(s) available to you: {'JP': false, 'US': true}
Change your DNS to xxx.xxx.xxx.xxx and start watching Netflix out of region.
Done!

Then went and added my droplet's IP to DNS settings.  Then went to visit Netflix and got the same results.

I don't understand what you meant by "DO's address space is blocked." Do you mean this method will no longer work with DO?

**Comment by kyle95wm** [comment]
hmm interesting. Have you tried destroying and re-building a new droplet in another location? I haven't had ANY problems with this method (haven't had to rebuild my server for a long time)

What I meant by "DO's address space" is DO offers native IPV6 support, but sadly Netflix has blocked that address space from working hence the reason we're using HE's tunnels. Maybe @ab77 can better assist you in troubleshooting.

**Comment by kyle95wm** [comment]
Remember, DO NOT ENABLE IPV6 during droplet creation. Also remember to log out of netflix and log back in. Clear cache, cookies, etc just to be on the safe side

**Comment by kyle95wm** [comment]
Im building a test server in the UK. I'll let you know how things go on my end.

**Comment by kyle95wm** [comment]
Okay so I get the following output:


root@test:~# git clone https://github.com/ab77/netflix-proxy /opt/netflix-proxy && cd /opt/netflix-proxy && ./build.sh -u xxxx -p xxxx -n 2 # this was because I have more than 1 tunnel
Cloning into '/opt/netflix-proxy'...
remote: Counting objects: 3379, done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 3379 (delta 11), reused 0 (delta 0), pack-reused 3328
Receiving objects: 100% (3379/3379), 106.78 MiB | 22.21 MiB/s, done.
Resolving deltas: 100% (1715/1715), done.
Checking connectivity... done.
resolved params: clientip=99.238.208.95 ipaddr=178.62.116.223 extip=178.62.116.223
cmd: ./build.sh -r=1 -b=0 -s= -z=0 -n=2 -u=kyle95wm -p [secret] -k [secret]

 * disabling native IPv6 on eth0...                                      [ OK ] 
 * installing XPath...                                                   [ OK ] 
 * enabling he-ipv6 interface...                                         [ OK ] 
 * bringing up IPv6 tunnel...                                            [ OK ] 
 * testing IPv6 tunnel (this may take a while)...                        [ OK ] 
 * enabling DNS recursion...                                             [ OK ] 
 * authorising clientip=x.x.x.x on iface=eth0...                   [ OK ] 
 * adding IPv4 iptables rules...                                         [ OK ] 
 * creating Docker and sniproxy configuration templates...               [ OK ] 
 * checking IPv6 connectivity...                                                 * enabling sniproxy IPv6 priority...                                    [ OK ] 
 * installing sipcalc...                                                 [ OK ] 
 * enabling Docker IPv6 dual-stack support with fixed-cidr-v6=2001:470:1f1d:593::/64...                                                                  [ OK ] 
 * adding IPv6 iptables rules...                                         [ OK ] 
 * installing iptables|netfilter-persistent service...                   [ OK ] 
 * socialising Docker with iptables-persistent service...                [ OK ] 
 * updating iptables-persistent init script...                           [ OK ] 
 * saving iptables rules...                                              [ OK ] 
 * creating zones.override from template...                              [ OK ] 
 * updating db.override with extip=x.x.x.x and date=20160528...   [ OK ] 
 * installing python-pip and docker-compose...                           [ OK ] 
 * configuring netflix-proxy-admin backend...                            [ OK ] 
 * configuring netflix-proxy-admin reverse-proxy...                      [ OK ] 
 * creating and starting Docker containers...                            [ OK ] 
 * configuring upstart...                                                [ OK ] 
 * reloading ipables rules...                                            [ OK ] 
 * no specific steps to execute for Ubuntu at this time...               [ OK ] 
 * testing DNS...                                                        [ OK ] 
 * testing proxy (OpenSSL)...                                            [ OK ] 
 * testing proxy (cURL)...                                               [ OK ] 
 * testing netflix-proxy admin site...                                   [ OK ] 

netflix-proxy-admin site=http://x.x.x.x:8080/ credentials=admin:TxgRvsVXkd
IPv6=Enabled
caching-resolver=Disabled
Hulu region(s) available to you: {'JP': false, 'US': false}
Change your DNS to nope.you.cant.have.it and start watching Netflix out of region.
Done!
root@test:/opt/netflix-proxy# 

Okay so I tried the server out and was able to play UK content (Stargate: The Ark of Truth

**Comment by kyle95wm** [comment]
Here's a video tutorial [https://www.youtube.com/watch?v=8DrNgnq_cdM](url)

**Comment by jquiambao** [comment]
Hey thanks for the video!

I haven't tried it out yet, but it looks like I missed the entire HE process! (I should RTFM more) I'm pretty sure that's all I needed to get this thing working.

**Comment by kyle95wm** [comment]
Yeah no problem. That error in the video was because I was redo rog my screen. I guess Netflix doesn't like people "mirroring" their content that includes screen recorders.

**Comment by ab77** [comment]
Thanks @kyle95wm. Happy to link to that video in the readme somewhere if you think it is useful.

**Comment by kyle95wm** [comment]
Yeah sure go ahead I don't mind.
