### ISSUE TITLE
BBC iPlayer - 'Content not working'

### ISSUE THREAD

**Issue by pjbish** [ab77/netflix-proxy#186]
Firstly, great work with this project :-)

I've got a strange one to report, and hope that someone in the community can help with. I have a proxy setup with Kamatera UK. Essentially a sandbox. Setup using the scripts and instructions on the main page.

Works fine for Netflix UK & iPlayer (for 99% of content), however, I've noticed an error( "content doesn't appear to be working - Try again") on some of the recent feeds from Glastonbury. What's even stranger is that with these feeds, they error on one day, and then work fine the following day. It seems that perhaps they error on the day that they're still considered to be a 'stream', and then they are moved to VOD, and work fine.

I've traced the DNS through Chrome while trying to access the streams that error, and noticed a couple of new addresses which I've added to the zones.overrride (see below).

zone "vod-rtmp-uk-live.edgesuite.net." {
    type master;
    file "/data/conf/db.override";
};

zone "bbcfmt.fcod.llnwd.net." {
    type master;
    file "/data/conf/db.override";
};

Even though when I retry, I can see that these then become directed to the Proxy, the same error persists (until I try and access the same stream the following day). 

Just to further confuse things, I've run another test with a VPN. I've configured a DO UK VPN box to point at the same proxy (Kamatera UK). When I connect to this box by VPN, and try and access the content that is failing, it plays fine. Go figure ???

An example of the content that is failing is here:

http://www.bbc.co.uk/programmes/p03zhqnz

This one's stumped me, so I'm hoping it makes sense to someone in this community. I'm based in Australia BTW.

**Comment by ab77** [comment]
Sounds suspiciously like browser caching... Have you tried doing all of this in Chrome Incognito mode?

**Comment by pjbish** [comment]
Yes. Different browsers and devices and incognito.

**Comment by ab77** [comment]
This only other thing I can think of is that `fcod` is Limelight's Flash Media Server endpoint and `rtmp` is probably the same for Akamai as opposed to HLS and HDS, which are Smooth Streaming/HLS/DASH endpoints. Maybe clear the Flash player caches as well?

**Comment by ab77** [comment]
From my recent testing, it appears BBC iPlayer doesn't always use DNS to resolve media hosts. So just replying on DNS fudging isn't going to work, because the media IPs are shipped to the player in a proprietary payload, with the player then making direct to IP requests. I believe Netflix also uses this approach in some of their apps (e.g. iOS).

Unfortunately, a DNS/proxy solution won't work here and to get around this, interesting traffic must be re-routed. There is extensive discussion and example (OpenWRT) implementation in thread https://github.com/ab77/netflix-proxy/issues/180 on how to get around this.

-- ab1
