### ISSUE TITLE
Enabled IPs

### ISSUE THREAD

**Issue by cojarbi** [ab77/netflix-proxy#199]
Guys, wonderfully solution this is. I'm wondering / looking for a way to display all enabled IP.  Where can I find this? 

Thanks in advance

**Comment by ab77** [comment]
You are probably looking for `/opt/netflix-proxy/data/conf/zones.override`.

**Comment by cojarbi** [comment]
Anton

That I beleive I'd for the service IP. I'm looking for the list of customer enabled IP

Thanks

AY

**Comment by ab77** [comment]
Oh, in that case, run `iptables-save | grep PREROUTING | grep ACCEPT` or `sqlite3 /opt/netflix-proxy/auth/db/auth.db "select * from ipaddrs;"`.

**Comment by ab77** [comment]
Please register for updates on the mailing list (http://netflix-proxy.belodedenko.me/) RE: August update. An alternative (paid subscription based) unblocking solution is close to being completed and should be going to trial soon.

**Comment by Huskion** [comment]
I'm looking to add a group of IP addresses using an ip block, effectively allowing any client from any IP in the block to use the proxy without the need for authentication. On a previous version that didn't have the login interface/sqlite database, it was possible to do this by adding iptables rules such as 
-A FRIENDS -s n.n.n.n/nn -j ACCEPT
with the CIDR suffix after the IP. How would I go about adding entries like this now? The interface says that "this is not a valid IPv4 address" otherwise.

**Comment by ab77** [comment]
the auth portal only works with `/32` mask (i.e. single IP). You probably want to run this manually on the command line (or update the `auth.py` code):

```
export ipaddr_mask=192.168.100.0/24 # change this
export IFACE=eth0 # check this
iptables -t nat -A PREROUTING -s ${ipaddr_mask} -i ${IFACE} -j ACCEPT && \
  iptables-save >/etc/iptables/rules.v4
```

**Comment by Huskion** [comment]
For now I have edited /etc/iptables/rules.v4 manually and inserted my rules, then used iptables-restore to retrieve them. Does this work permanently, or will the inconsistencies with the sqlite database cause the rules to get overwritten if I restart the service?

**Comment by ab77** [comment]
That will work. Permanently. The rules are reloaded from those files every time the server is restarted. Adding IPs via the web portal, won't affect these custom rules.
