### ISSUE TITLE
great firewall china still working?

### ISSUE THREAD

**Issue by fatsmack** [ab77/netflix-proxy#232]
I have a friend in china that I have helped install this onto a private VPS to access facebook and twitter and a random test site. We ping facebook.com on china computer and it resolves to facebook address (not the vps IP) and ping fails. We then ping the random test site we added into zones override and it resolves perfectly to VPS ip. 

Do you think china have upgraded their efforts and are intercepting, or could we be doing something wrong? We followed the link provided in readme and added all domains but no luck.

**Comment by ab77** [comment]
There is a packet inspection firewall between you and the rest of the Internet, which is operated by your government. The firewall is probably re-writing your DNS requests to their internal DNS servers, which means the DNS request will never make it out to your VPS. You could try OpenVPN over stunnel instead of DNS/proxy.

**Comment by ab77** [comment]
You could also try: http://black-box.belodedenko.me/ is cloak-mode (Stunnel).
