### ISSUE TITLE
cant play amazon prime video

### ISSUE THREAD

**Issue by andresmorago** [ab77/netflix-proxy#288]
hello
has anyone been able to play content from amazon video recently? i have several servers configured to be redirected to my usa server but still, amazon wont let me play any videos

```
#AMAZON
server=/fls-na.amazon.com/xx.xx.xx.xx
server=/fals.atv-ps.amazon.com/xx.xx.xx.xx
server=/cloudfront.net/xx.xx.xx.xx
server=/amazonvideo.com/xx.xx.xx.xx
server=/primevideo.com/xx.xx.xx.xx
server=/amazon.com/xx.xx.xx.xx
server=/atv-ext.amazon.com/xx.xx.xx.xx
server=/atv-ps.amazon.com/xx.xx.xx.xx
server=/ssl-images-amazon.com/xx.xx.xx.xx
server=/ecx.images-amazon.com/xx.xx.xx.xx
server=/fals.atv-ps.amazon.com/xx.xx.xx.xx
server=/atv-ps.amazon.com/xx.xx.xx.xx
server=/m.media-amazon.com/xx.xx.xx.xx
server=/atv-ext.amazon.com/xx.xx.xx.xx
server=/images-na.ssl-images-amazon.com/xx.xx.xx.xx
server=/g-ecx.images-amazon.com/xx.xx.xx.xx
server=/amazon-adsystem.com/xx.xx.xx.xx
server=/e673.e9.akamaiedge.net/xx.xx.xx.xx
server=/a875.w67.akamai.net/xx.xx.xx.xx
server=/a48.w48.akamai.net/xx.xx.xx.xx
```

**Comment by rami84** [comment]
Same issue here as well, I only can play in on PC on Amazon.com website but not on Android phone or Fire TV
I get this error:
we're unable to connect to Amazon video. Please verify your device's internet connection

**Comment by ab77** [comment]
You don't need to break out individual hosts, just use this [list](https://github.com/ab77/netflix-proxy/blob/master/proxy-domains.txt).

**Comment by rami84** [comment]
I was using this one: 
<pre>
bind-dynamic
bogus-priv
domain-needed
log-facility=-
local-ttl=60
address=/akadns.net/xx.xx.xx.xx
address=/akam.net/xx.xx.xx.xx
address=/akamai.com/xx.xx.xx.xx
address=/akamai.net/xx.xx.xx.xx
address=/akamaiedge.net/xx.xx.xx.xx
address=/akamaihd.net/xx.xx.xx.xx
address=/akamaistream.net/xx.xx.xx.xx
address=/akamaitech.net/xx.xx.xx.xx
address=/akamaitechnologies.com/xx.xx.xx.xx
address=/akamaitechnologies.fr/xx.xx.xx.xx
address=/akamaized.net/xx.xx.xx.xx
address=/edgekey.net/xx.xx.xx.xx
address=/edgesuite.net/xx.xx.xx.xx
address=/srip.net/xx.xx.xx.xx
address=/footprint.net/xx.xx.xx.xx
address=/llnwd.net/xx.xx.xx.xx
address=/edgecastcdn.net/xx.xx.xx.xx
address=/cloudfront.net/xx.xx.xx.xx

address=/netflix.com/xx.xx.xx.xx
address=/netflix.net/xx.xx.xx.xx
address=/nflximg.net/xx.xx.xx.xx
address=/nflxvideo.net/xx.xx.xx.xx
address=/nflxso.net/xx.xx.xx.xx
address=/nflxext.com/xx.xx.xx.xx

address=/hulu.com/xx.xx.xx.xx
address=/huluim.com/xx.xx.xx.xx
address=/hbonow.com/xx.xx.xx.xx
address=/sling.com/xx.xx.xx.xx
address=/hbogo.com/xx.xx.xx.xx
address=/amazon.com/xx.xx.xx.xx
address=/primevideo.com/xx.xx.xx.xx
address=/ssl-images-amazon.com/xx.xx.xx.xx

address=/amazon.co.uk/52.56.172.20
address=/crackle.com/xx.xx.xx.xx
address=/pandora.com/xx.xx.xx.xx
address=/vudu.com/xx.xx.xx.xx
address=/blinkbox.com/xx.xx.xx.xx
address=/abc.com/xx.xx.xx.xx
address=/fox.com/xx.xx.xx.xx
address=/theplatform.com/xx.xx.xx.xx
address=/nbc.com/xx.xx.xx.xx
address=/nbcuni.com/xx.xx.xx.xx
address=/ip2location.com/xx.xx.xx.xx
address=/pbs.org/xx.xx.xx.xx
address=/warnerbros.com/xx.xx.xx.xx
address=/southpark.cc.com/xx.xx.xx.xx
address=/cbs.com/xx.xx.xx.xx
address=/brightcove.com/xx.xx.xx.xx
address=/cwtv.com/xx.xx.xx.xx
address=/spike.com/xx.xx.xx.xx
address=/go.com/xx.xx.xx.xx
address=/mtv.com/xx.xx.xx.xx
address=/mtvnservices.com/xx.xx.xx.xx
address=/playstation.net/xx.xx.xx.xx
address=/uplynk.com/xx.xx.xx.xx
address=/maxmind.com/xx.xx.xx.xx
address=/disney.com/xx.xx.xx.xx
address=/disneyjunior.com/xx.xx.xx.xx
address=/xboxlive.com/xx.xx.xx.xx
address=/lovefilm.com/xx.xx.xx.xx
address=/turner.com/xx.xx.xx.xx
address=/amctv.com/xx.xx.xx.xx
address=/sho.com/xx.xx.xx.xx
address=/mog.com/xx.xx.xx.xx
address=/wdtvlive.com/xx.xx.xx.xx
address=/beinsportsconnect.tv/xx.xx.xx.xx
address=/beinsportsconnect.net/xx.xx.xx.xx
address=/fig.bbc.co.uk/yy.yy.yy.yy
address=/open.live.bbc.co.uk/yy.yy.yy.yy
address=/sa.bbc.co.uk/yy.yy.yy.yy
address=/bbc.co.uk/yy.yy.yy.yy
address=/bbci.co.uk/yy.yy.yy.yy
address=/vod-rtmp-uk-live.edgesuite.net/yy.yy.yy.yy
address=/vs-hds-uk-live.edgesuite.net/yy.yy.yy.yy
address=/vs-hls-uk-live.edgesuite.net/yy.yy.yy.yy
address=/vod-hds-uk-live.edgesuite.net/yy.yy.yy.yy
address=/vod-hls-uk-live.edgesuite.net/yy.yy.yy.yy
address=/bbcfmt.vo.llnwd.net/yy.yy.yy.yy
address=/bbcfmt.fcod.llnwd.net/yy.yy.yy.yy

address=/itv.com/yy.yy.yy.yy

address=/crunchyroll.com/xx.xx.xx.xx
address=/ifconfig.co/xx.xx.xx.xx
address=/spotify.com/xx.xx.xx.xx
address=/showmax.com/xx.xx.xx.xx
address=/starz.com/xx.xx.xx.xx
address=/starzplay.com/xx.xx.xx.xx
address=/popcornflix.com/xx.xx.xx.xx
address=/unreel.me/xx.xx.xx.xx
</pre>

I will compare it to the one you sent
For now I see this line that is not in my list:
amazonvideo.com

**Comment by rami84** [comment]
@ab77 Now I'm getting geographical restrictions error with USA content but I can run the ones in my country content list

**Comment by ab77** [comment]
Does it still unblock US content in a browser?

**Comment by rami84** [comment]
Browser is working fine with both conf (mine and yours)

**Comment by ab77** [comment]
OK, then first try null routing Google and all the other public (well known) DNS IPs on your router. Then, replace all `address=` directives with `address=/#/x.x.xx`, which will resolve everything to your proxy.

If that doesn't work, your boxes probably don't support SNI.

**Comment by rami84** [comment]
I'll give this a try
It was working before for me on the same devices (Android phone and Fire TV Stick)
Thanks

**Comment by andresmorago** [comment]
rami84, on what file do you modify the servers? i see a different format than mine

**Comment by rami84** [comment]
@andresmorago I have it configured in dnsmasq.conf (I installed the script on a VPS)

**Comment by rami84** [comment]
@ab77 It's now working for me again
I not sure where the problem was but new installation make it work again
I only added this to your list in my config: 
ssl-images-amazon.com
That makes dnsmasq.conf file looks like this:
<pre>
bind-dynamic
bogus-priv
domain-needed
log-facility=-
local-ttl=60
address=/akadns.net/xx.xx.xx.xx
address=/akam.net/xx.xx.xx.xx
address=/akamai.com/xx.xx.xx.xx
address=/akamai.net/xx.xx.xx.xx
address=/akamaiedge.net/xx.xx.xx.xx
address=/akamaihd.net/xx.xx.xx.xx
address=/akamaistream.net/xx.xx.xx.xx
address=/akamaitech.net/xx.xx.xx.xx
address=/akamaitechnologies.com/xx.xx.xx.xx
address=/akamaitechnologies.fr/xx.xx.xx.xx
address=/akamaized.net/xx.xx.xx.xx
address=/edgekey.net/xx.xx.xx.xx
address=/edgesuite.net/xx.xx.xx.xx
address=/srip.net/xx.xx.xx.xx
address=/footprint.net/xx.xx.xx.xx
address=/llnwd.net/xx.xx.xx.xx
address=/edgecastcdn.net/xx.xx.xx.xx
address=/cloudfront.net/xx.xx.xx.xx

address=/netflix.com/xx.xx.xx.xx
address=/netflix.net/xx.xx.xx.xx
address=/nflximg.net/xx.xx.xx.xx
address=/nflxvideo.net/xx.xx.xx.xx
address=/nflxso.net/xx.xx.xx.xx
address=/nflxext.com/xx.xx.xx.xx

address=/hulu.com/xx.xx.xx.xx
address=/huluim.com/xx.xx.xx.xx
address=/hbonow.com/xx.xx.xx.xx
address=/sling.com/xx.xx.xx.xx
address=/hbogo.com/xx.xx.xx.xx
address=/amazon.com/xx.xx.xx.xx
address=/amazonvideo.com/xx.xx.xx.xx
address=/ssl-images-amazon.com/xx.xx.xx.xx

address=/amazon.co.uk/yy.yy.yy.yy
address=/crackle.com/xx.xx.xx.xx
address=/pandora.com/xx.xx.xx.xx
address=/vudu.com/xx.xx.xx.xx
address=/blinkbox.com/xx.xx.xx.xx
address=/abc.com/xx.xx.xx.xx
address=/fox.com/xx.xx.xx.xx
address=/theplatform.com/xx.xx.xx.xx
address=/nbc.com/xx.xx.xx.xx
address=/nbcuni.com/xx.xx.xx.xx
address=/ip2location.com/xx.xx.xx.xx
address=/pbs.org/xx.xx.xx.xx
address=/warnerbros.com/xx.xx.xx.xx
address=/southpark.cc.com/xx.xx.xx.xx
address=/cbs.com/xx.xx.xx.xx
address=/brightcove.com/xx.xx.xx.xx
address=/cwtv.com/xx.xx.xx.xx
address=/spike.com/xx.xx.xx.xx
address=/go.com/xx.xx.xx.xx
address=/mtv.com/xx.xx.xx.xx
address=/mtvnservices.com/xx.xx.xx.xx
address=/playstation.net/xx.xx.xx.xx
address=/uplynk.com/xx.xx.xx.xx
address=/maxmind.com/xx.xx.xx.xx
address=/disney.com/xx.xx.xx.xx
address=/disneyjunior.com/xx.xx.xx.xx
address=/xboxlive.com/xx.xx.xx.xx
address=/lovefilm.com/xx.xx.xx.xx
address=/turner.com/xx.xx.xx.xx
address=/amctv.com/xx.xx.xx.xx
address=/sho.com/xx.xx.xx.xx
address=/mog.com/xx.xx.xx.xx
address=/wdtvlive.com/xx.xx.xx.xx
address=/beinsportsconnect.tv/xx.xx.xx.xx
address=/beinsportsconnect.net/xx.xx.xx.xx
address=/fig.bbc.co.uk/yy.yy.yy.yy
address=/open.live.bbc.co.uk/yy.yy.yy.yy
address=/sa.bbc.co.uk/yy.yy.yy.yy
address=/bbc.co.uk/yy.yy.yy.yy
address=/bbci.co.uk/yy.yy.yy.yy
address=/vod-rtmp-uk-live.edgesuite.net/yy.yy.yy.yy
address=/vs-hds-uk-live.edgesuite.net/yy.yy.yy.yy
address=/vs-hls-uk-live.edgesuite.net/yy.yy.yy.yy
address=/vod-hds-uk-live.edgesuite.net/yy.yy.yy.yy
address=/vod-hls-uk-live.edgesuite.net/yy.yy.yy.yy
address=/bbcfmt.vo.llnwd.net/yy.yy.yy.yy
address=/bbcfmt.fcod.llnwd.net/yy.yy.yy.yy

address=/itv.com/yy.yy.yy.yy

address=/crunchyroll.com/xx.xx.xx.xx
address=/ifconfig.co/xx.xx.xx.xx
address=/spotify.com/xx.xx.xx.xx
address=/showmax.com/xx.xx.xx.xx
address=/starz.com/xx.xx.xx.xx
address=/starzplay.com/xx.xx.xx.xx
address=/popcornflix.com/xx.xx.xx.xx
address=/unreel.me/xx.xx.xx.xx
</pre>
Thanks for the great work :)

**Comment by ab77** [comment]
I'd love to know if `ssl-images-amazon.com` is really needed. Judging by the name alone, it feels like a red herring...

**Comment by rami84** [comment]
To be honest I'm not sure 
I may try to remove it and see what will happen

**Comment by rami84** [comment]
Removed it and everything still working fine :)

**Comment by ab77** [comment]
OK, thanks for double checking.

**Comment by andresmorago** [comment]
hi. 
sorry to reopen this. I have now reconfigured proxy with lastest version and amazon now works on my apple tv and samsung smart tv
when trying to play from my computer, i get this error

> Your device's Internet connection is using an HTTP proxy which prevents playing your video. Please close or disable any proxy programs and try again. For further assistance, please contact Amazon Customer Service at www.amazon.com/videohelp and refer to error 1042.
