### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by proxyrequired** [ab77/netflix-proxy#299]
i am not able to unblock fubo.tv

netflix mtv fox sports and hulu is working fine

do i have to enable the ipv6 for that

**Comment by ab77** [comment]
Has you added `fubo.tv` domain and tested it resolves to your proxy?

**Comment by proxyrequired** [comment]
no it's not working yet

i am trying again

**Comment by proxyrequired** [comment]
its working now but the videos are not coming

**Comment by ab77** [comment]
Fubo, like BBC iPlayer, use HTTP/2 protocol on their media/API endpoints, so this solution won't work unfortunately with default settings. (see  [n5](https://github.com/ab77/netflix-proxy#footnotes))

To make it work, you'll have to work out which Fubo hosts are different machines/clusters and pin them each to a different public IP.  However, since you are limited to the number your VPS provider will allow you to assign, this approach might not be practical.

The remaining and arguably easiest way is to use a VPN. You can try [unzoner.com](unzoner.com), which works with fubo.tv or any other VPN provider (best to as them first before you hand over the money).
