### ISSUE TITLE
DNS Lookup Failing

### ISSUE THREAD

**Issue by iveoles** [ab77/netflix-proxy#3]
Hi 

When setting up the server only Netflix lookups would work, I need to put in a secondary DNS (8.8.8.8) before other sites and the netflix CSS etc would work. Is it possible for the VPS to fallback to another DNS server if the lookup isn't caught in the redirect rules?

**Comment by ab77** [comment]
Hi there, yes it is, but because it requires enabling recursive lookups on your VPS, which is a security risk, I've disabled it by default.

If you wanted to enable recursive lookups, please see previous [issue](https://github.com/ab77/netflix-proxy/issues/2) on how to modify your config to enable recursive DNS lookups.

Once you enable it, please remember that the only barrier between your DNS and the big bad Internet is iptables. If you ever drop or relax the relevant rules, bad people may use your DNS server to attack others using [DNS amplification DDoS attack ](https://deepthought.isc.org/article/AA-00897/0/What-is-a-DNS-Amplification-Attack.html).

Cheers!

**Comment by iveoles** [comment]
Just so I know, it's safe (as anything can be) as long as I leave the iptables exactly as they are?

**Comment by ab77** [comment]
Correct, because by default, iptables only allow your home IP access to the
VPS and block all others.

**Comment by iveoles** [comment]
Oh, so you wouldn't be able to use this for a more public dns server?

**Comment by ab77** [comment]
In theory you could, but someone, somewhere may get upset if they find your
IP being used to DDoS others. In which case you may get an email from your
hosting provider asking you to "please secure your DNS".

If by "public" you mean having a limited set of people using your VPS
besides yourself, then you could just add their IPs to your iptables rule
set. This of course becomes a problem with dynamically allocated IPs. In
this case you could use a DynDNS service and use DNS names in your iptables
config, rather than IPs (slower).

In either case, passing all your DNS traffic via a server in another
country will work, but it does unnecessarily slow down your Internet
performance. Best to use some kind of DNS router on your local network
(like DNSmasq), so you can just send specific DNS requests (e.g. *.
netflix.com) to your VPS, but all the rest via your normal ISP DNS server.

Hope this helps..

-- ab1

**Comment by iveoles** [comment]
Ok. I was thinking of cycling them every week or so, not exactly the greatest protection but perhaps it'll be enough.

Does this mean I'll need to clear the iptables before anyone can use it? How does it know the home IP address to whitelist?

Thanks so much for your help. The whole implementation is fantastic!

**Comment by iveoles** [comment]
I know this may be asking a little much, but would it be possible to create a branch with the recursion turned on? If it's too much bother I can just fork it for my own use, but I wouldn't want to miss out on any future developments.

Thanks again!

**Comment by ab77** [comment]
Just keep in mind, that spinning up a new VPS, does not necessarily mean it
will get a new public IP every time. From my experience with DigitalOcean,
you tend to get the same one.

The build script get the home IP from the SSH_CLIENT environment variable,
since the assumption is that you are logged in from home.

I would not recommend clearing iptables, because you'll break Docker
communication with the host, among other things. Have a look
at /etc/iptables.rules, (e.g.):

...
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
*-A INPUT -s <your_home_ext__ip>/32 -p tcp -m tcp --dport 80 -j ACCEPT*
*-A INPUT -s <your_home_ext__ip>/32 -p tcp -m tcp --dport 443 -j ACCEPT*
-A INPUT -j REJECT --reject-with icmp-host-prohibited
...

The two bold lines permit access to HTTP/HTTPS proxy and DNS from your
home. You can add another pair of these lines below the existing ones,
replacing the IP address with your friend's IP and restarting iptables to
give them access to your setup. You can use a DNS name there as well, if
your friend/family use a DynDNS service, which always points to their
current dynamic IP.

When I have some spare time, I will add a flag to the build script to
specify whether recursion is desired or not and update the docs, but for
the time being, just use the manual method.

Cheers!

-- ab1

**Comment by ab77** [comment]
Hi there, I've now modified the build script to take some optional parameters to disable recursion for advanced users and leave it **re-enabled by default**. I suspect most people want this option on out of the box, to make it all work nicely, since not everyone has ability to selectively direct DNS requests to one or the other DNS server.

If you want to build with DNS recursion **disabled** for additional security, the command to run is:

`cd /opt && git clone https://github.com/ab77/netflix-proxy.git && cd netflix-proxy && ./build.sh -r 0 -b 1`

I've also updated the README. Let me know if there are any issues...

-- ab1
