### ISSUE TITLE
BBC iPlayer

### ISSUE THREAD

**Issue by 20Web** [ab77/netflix-proxy#42]
Re-opening an issue for the iPlayer as the other one is closed.

It seems that you can get onto a video and click 'Play' though it returns 'This content doesn't seem to be working' 

Any ideas?

**Comment by DavidCWGA** [comment]
Confirming that this is also affecting me, though I don't know a solution.

**Comment by DavidCWGA** [comment]
Actually, I do have a fix. I had to add a couple of extra domains the iplayer seems to be using:

```
zone "edgesuite.net." {
    type master;
    file "/data/db.override";
};

zone "2cnt.net." {
    type master;
    file "/data/db.override";
};
```

This seems to fix it.

**Comment by DavidCWGA** [comment]
Experimenting with the Kodi plugins, the domains above only seem to work for the Akamai CDN. The BBC also use the Limelight CDN, and you'll probably need different domains for that, though I don't know what they are. If you're using the iPlayer through a web browser, you obviously don't get to pick which CDN you're using.

**Comment by DavidCWGA** [comment]
...limelight appears to be llnwd.net.

**Comment by belodedenko** [comment]
Right, thanks for your input guys. I've had some time to have a look at this and I am afraid the news isn't good. It appears, BBC have made a move to geo-blocking on their CDN endpoints, at least for all the new HD content since I've put this solution together.

To demonstrate the problem, here is a [sample show](http://www.bbc.co.uk/iplayer/episode/b06l1stp/dont-tell-the-bride-series-10-1-katie-kyle) I picked off the front page.

I captured the calls iPlayer (web version) makes to stream this show and the item of interest is [here](http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/pc/vpid/b06l1rmh/atk/515bb27f3c92c16992628311ff2fc6efd0c709c6/asn/1/) payload, specifically:

    <media bitrate="8490" encoding="h264" expires="2015-11-27T22:00:00Z" height="1080" kind="video" service="stream-uk-pc_streaming_concrete_combined_sd" type="video/mp4" width="1920">
        <connection authExpires="2015-10-29T18:31:02+00:00" authExpiresOffset="33029" dpw="50" href="http://vod-hds-uk-live.edgesuite.net/usp/auth/vod/piff_abr_full_hd/e1175a-b06l1rmh/vf_b06l1rmh_4f689afb-d1a8-40ca-9402-bb993d1ed3ec.ism/pc_hd_abr_v1_hds_master.f4m?__gda__=1446132033_8326af2a611925740d2bd0a95e95f2a1" priority="1" protocol="http" supplier="mf_akamai_uk_hds" transferFormat="hds"/>
        <connection authExpires="2015-10-29T19:21:48+00:00" authExpiresOffset="36075" dpw="50" href="http://vod-dash-uk-live.edgesuite.net/usp/auth/vod/piff_abr_full_hd/e1175a-b06l1rmh/vf_b06l1rmh_4f689afb-d1a8-40ca-9402-bb993d1ed3ec.ism/pc_hd_abr_v1_dash_master.mpd?__gda__=1446132033_14f22c6d55c8ae03a00801e430059ed3" priority="1" protocol="http" supplier="mf_akamai_uk_dash" transferFormat="dash"/>
        <connection authExpires="2015-10-29T14:12:36+00:00" authExpiresOffset="17523" href="http://vod-hds-uk-live.bbcfmt.vo.llnwd.net/usp/auth/vod/piff_abr_full_hd/e1175a-b06l1rmh/vf_b06l1rmh_4f689afb-d1a8-40ca-9402-bb993d1ed3ec.ism/pc_hd_abr_v1_hds_master.f4m?s=1446088833&e=1446132033&h=b4f5a2ab7430891c582a06ccc266f3ba" priority="2" protocol="http" supplier="mf_limelight_uk_hds" transferFormat="hds"/>
        <connection authExpires="2015-10-29T14:16:39+00:00" authExpiresOffset="17766" href="http://vod-dash-uk-live.bbcfmt.vo.llnwd.net/usp/auth/vod/piff_abr_full_hd/e1175a-b06l1rmh/vf_b06l1rmh_4f689afb-d1a8-40ca-9402-bb993d1ed3ec.ism/pc_hd_abr_v1_dash_master.mpd?s=1446088833&e=1446132033&h=2c4788b25979969e958bba9567ac9ba6" priority="2" protocol="http" supplier="mf_limelight_uk_dash" transferFormat="dash"/>
    </media>

The two CDNs BBC iPlayer now uses to deliver adaptive HD bitrate streams over HTTP are `Akamai` and `Limelight`. Both now implement geo-fencing on the edge, which means trying to access this content from outside of the geo-fenced area, will result in errors. Interestingly, the HTTP error is different between `Akamai` and `Limelight` (e.g. from a US location).

Limelight returns HTTP 400:

	~# curl -v -o /dev/null 'http://vod-hds-uk-live.bbcfmt.vo.llnwd.net/usp/auth/vod/piff_abr_full_hd/e1175a-b06l1rmh/vf_b06l1rmh_4f689afb-d1a8-40ca-9402-bb993d1ed3ec.ism/pc_hd_abr_v1_hds_master.f4m?s=1446088833&e=1446132033&h=b4f5a2ab7430891c582a06ccc266f3ba'
	* Connected to vod-hds-uk-live.bbcfmt.vo.llnwd.net (208.111.160.6) port 80 (#0)
	> GET /usp/auth/vod/piff_abr_full_hd/e1175a-b06l1rmh/vf_b06l1rmh_4f689afb-d1a8-40ca-9402-bb993d1ed3ec.ism/pc_hd_abr_v1_hds_master.f4m?s=1446088833&e=1446132033&h=b4f5a2ab7430891c582a06ccc266f3ba HTTP/1.1
	> User-Agent: curl/7.35.0
	> Host: vod-hds-uk-live.bbcfmt.vo.llnwd.net
	> Accept: */*
	>
	< HTTP/1.1 400 Bad Request
	* Server EdgePrism/4.2.9.0 is not blacklisted
	< Server: EdgePrism/4.2.9.0
	< Mime-Version: 1.0
	< Content-Type: text/plain
	< Date: Thu, 29 Oct 2015 09:24:49 GMT
	< Content-Length: 0
	< Connection: keep-alive
	< Access-Control-Allow-Headers: Origin, Range, Accept-Encoding, Referer
	< Access-Control-Allow-Origin: *
	< Access-Control-Expose-Headers: Server, Range, Content-Length, Content-Range

And Akamai returns a HTTP 403:

	~# curl -v 'http://vod-hds-uk-live.edgesuite.net/usp/auth/vod/piff_abr_full_hd/e1175a-b06l1rmh/vf_b06l1rmh_4f689afb-d1a8-40ca-9402-bb993d1ed3ec.ism/pc_hd_abr_v1_hds_master.f4m?__gda__=1446132033_8326af2a611925740d2bd0a95e95f2a1'
	* Connected to vod-hds-uk-live.edgesuite.net (23.67.246.122) port 80 (#0)
	> GET /usp/auth/vod/piff_abr_full_hd/e1175a-b06l1rmh/vf_b06l1rmh_4f689afb-d1a8-40ca-9402-bb993d1ed3ec.ism/pc_hd_abr_v1_hds_master.f4m?__gda__=1446132033_8326af2a611925740d2bd0a95e95f2a1 HTTP/1.1
	> User-Agent: curl/7.35.0
	> Host: vod-hds-uk-live.edgesuite.net
	> Accept: */*
	>
	< HTTP/1.1 403 Forbidden
	* Server AkamaiGHost is not blacklisted
	< Server: AkamaiGHost
	< Mime-Version: 1.0
	< Content-Type: text/html
	< Content-Length: 509
	< Expires: Thu, 29 Oct 2015 09:27:27 GMT
	< Date: Thu, 29 Oct 2015 09:27:27 GMT
	< Connection: keep-alive
	<
	<HTML><HEAD>
	<TITLE>Access Denied</TITLE>
	</HEAD><BODY>
	<H1>Access Denied</H1>

	Access Denied

	You don't have permission to access "http://vod-hds-uk-live.edgesuite.net/usp/auth/vod/..." on this server.
	Reference #18.76f64317.1446110847.116cb3b4
	</BODY>
	</HTML>

Unfortunately the only two work arounds for this problem are (a) use a VPN to forward all traffic via a remote host; or (b) insert the following domains into your `zones.override.conf` file:

	zone "vod-hds-uk-live.edgesuite.net." {
		type master;
		file "/data/db.override";
	};

	zone "vod-hds-uk-live.bbcfmt.vo.llnwd.net." {
		type master;
		file "/data/db.override";
	};

This will allow BBC iPlayer to work, while preventing `Akamai` and `Limelight` CDN endpoints for other services being proxied unnecessarily. I also don't think `2cnt.net` is relevant here, since it is for marketing/analytics.

Also please note, that since this change effectively means you are now streaming video/audio content via the UK proxy, you will probably eat up your allocated VPS bandwidth allowance a lot quicker and the bitrate/quality of video will probably decrease as a result of higher latency between `<insert your country here>` and UK.

Hope this helps..

-- ab1

**Comment by DavidCWGA** [comment]
Thanks for the more specific hostnames. Yes, the video stream is now going through myVPS. I kinda expected that would ultimately be necessary. iPlayer now blocks known VPNs so there aren't many other options.

Thanks!

**Comment by belodedenko** [comment]
Well, I guess you could always deploy a bigger sized droplet to get extra GBs or move to another all-you-can-eat VPS.

-- ab1

**Comment by alexp2015** [comment]
Thanks for that.

As for bandwidth, no need to upgrade droplets *yet* as DO unofficially provides each package with unlimited. No charges or suspensions for going over.

This of course will change once they implement a bandwidth monitor in the control panel showing monthly usage though it's been in progress for a couple years so yeah :)

**Comment by ab77** [comment]
Oh, that's a relief :)

**Comment by qeirik** [comment]
A little addition to the solution that might come in handy. Adding those specific CDN endpoints was quite enough for my Chromium/Linux machine, however it didn't work for Kodi/OpenELEC box using http://github.com/vonH/plugin.video.iplayerwww. I don't know the exact reasons but it seems to use different CDNs. I made a little research and found out you have to add the following CDNs to your zones.override

```
zone "vs-hds-uk-live.edgesuite.net." {
    type master;
    file "/data/db.override";
};

zone "vs-hds-uk-live.bbcfmt.vo.llnwd.net." {
    type master;
    file "/data/db.override";
};

zone "vod-hls-uk-live.edgesuite.net." {
    type master;
    file "/data/db.override";
};

zone "vod-hls-uk-live.bbcfmt.vo.llnwd.net." {
    type master;
    file "/data/db.override";
};

```

specifically, vs-hds* works for live streams and vod-hls* for vod episodes
