### ISSUE TITLE
Raspberry implementation

### ISSUE THREAD

**Issue by andresmorago** [ab77/netflix-proxy#56]
Hello again ab.
This isnt an issue, i just dont know if this is the right place to ask you about it:

Due to the information you provided me a couple days ago, i have been thinking on a different approach for your netflix-proxy at my place and would like your advise if possible:

I have a unlimited bandwidth PPTP server located on USA. This server has an US public ip XXX and local ip 192.168.1.1

At my home (outside USA) i have a wireless router (it runs dnsmasq) with 10.0.0.1 address. this one gets a public ip YYY.
I also have a raspberry pi on this same network (10.0.0.27) and connected via wireless (interface wlan0). i installed a PPTP client and can connect to my USA server via ppp0 interface. It gets a 192.168.1.50 ip address on that interface with gateway 192.168.1.1 (my USA server).

Can i install your docker image on my raspberry and have it serve some of my local router dns requests? also i would need to route all of the docker image traffic through the ppp0 interface so it goes straight to my USA server. can this be possible somehow?

![fullsizerender](https://cloud.githubusercontent.com/assets/13720514/12429319/8c3f429e-beb7-11e5-8d61-1d6a3b5d48d6.jpg)

thanks so much in advance for your advise.

andres

**Comment by ab77** [comment]
Hi, if you already have a VPN terminating in the US, you should just route your traffic via that server, which means that the traffic will exit onto the Internet via your VPN server's public IP address in the US.

You'll have to change default gateway on your router and set up some static routes to do that. You should also investigate terminating the VPN on your router (rather than Pi), which would make the routing less convoluted.

Once you get that working, you can start selectively routing only certain IP addresses through your VPN, for example DNS (Google, OpenDNS or your VPN provider's DNS) and Netflix IPs (although you may have a hard time finding them all).

-- ab1

**Comment by lbdroid** [comment]
While preferable / simpler to [get your head around] putting the proxy on the remote USA server, it is certainly possible to rig it up as you ( @andresmorago ) suggest. Basically, you set up the VPN connection from either the router or the raspberry pi to the USA server, making sure to set the raspberry pi's **default route** and **DNS server** through the VPN. It doesn't matter at all which machine the VPN is running from, as long as the raspberry pi can get through it.

You then use dnsmasq on the router to direct the appropriate domain name lookups to the raspberry pi's IP address. Unlike a typical setup for having the proxy on the remote side, you WILL NOT have to meddle with virtual IP addresses or iptables, since the DNS lookups will yield a proper IP address on your local network.

**Comment by lbdroid** [comment]
And for extra credit, implement your VPN using two tun devices tied together using SSH :)

**Comment by andresmorago** [comment]
thank you both!. I will start working on this and come up her with more questions if i have them

**Comment by ab77** [comment]
I'll close for now, please re-open when/if you decide to revisit.
