### ISSUE TITLE
netflix vpn crackdown

### ISSUE THREAD

**Issue by Ted-setsys** [ab77/netflix-proxy#57]
Anyone else had problems recently with this setup?  I've only been running these docker images a few weeks, worked fine, until a few days ago...now, I can still search for/see US titles, but can't actually play them anymore.  Only US titles are affected, anything local works perfectly fine.

**Comment by lesnox** [comment]
It's ont Netflix who blocked VPN on US ?

**Comment by ab77** [comment]
About three days ago I tested using Digital Ocean VPS in San Francisco
using Google Chrome as was able to switch catalogues between UK and US.

There is some lag in catalogue refresh it seems after your re-point DNS, so
it isn't instant. It might help logging it with another device, which
hasn't been logged in to Netflix for a bit (e.g. iOS, ATV, etc.).

Pick a title which you know isn't in your local catalogue (see,
http://netflixukvsusa.blogspot.co.uk/), switch DNS, clear DNS cache and
browser gunk, wait and don't forget to switch off IPv6.

-- ab1

**Comment by newsera** [comment]
I think Netflix blocked Ramnode IP Range.

**Comment by lesnox** [comment]
GO to ovh ! The VPS is not so expensive and we can have a located ip ;)

**Comment by newsera** [comment]
Is OVH working for Netflix?

**Comment by lesnox** [comment]
Yes !!! :)  have one 2,99€ /HT

Envoyé de mon iPhone

**Comment by lbdroid** [comment]
Looks like as of yesterday, they've added Amazon (or at least a subset of it that I was using) to the block list.

**Comment by hyperperforator** [comment]
Doesn't work on DigitalOcean anymore either

**Comment by ab77** [comment]
That is unfortunate. All my testing seems to suggest it is still working fine, but perhaps Netflix have started blocking individual IPs within DO allocations.

Perhaps try a different provider, like AWS EC2 with an elastic IP or Microsoft Azure (free 30 day trial).

Also, if you set up HE TunnelBroker IPv6 tunnel, it is likely you will get the Netflix US catalogue by default. This is an odd one, but it seems to be the case with my setup in London, using Chrome browser.

**Comment by lbdroid** [comment]
@ab77 : like I said, amazon is blocked.
Until/unless netflix reduces their attack rate, its likely turning into a long term game of whack-a-mole.

Best bet is to do what I'm doing, which is installing something on a US resident's home network. I put haproxy with sni configs on an openwrt box at one, and a raspberry pi with similar haproxy config at another. From there, a reverse ssh tunnel using autossh back to the client end (need dynamic dns service or static IP) and you're golden. They aren't going to be killing IP's with 2-3-4 netflix accounts hooking through, just the ones that are feeding hundreds. Remember that it doesn't need to be a fast connection, since they are blocking via the authentication/control servers (very low data volume), not the data servers, which means that you can continue to pull the data directly off the CDN.

Should be able to easily substitute in your choice of proxy software like sniproxy. I use haproxy mainly because it is a standard package for most linux distros (i.e. openwrt, raspbian), and known to work with chromecast. Don't know if anything has changed, but last thing I heard was that chromecast and sniproxy don't get along particularly well; https://github.com/dlundquist/sniproxy/issues/64

**Comment by ab77** [comment]
That approach seems reasonable, as long as you can find willing US
residents :)

**Comment by lbdroid** [comment]
Not that difficult, they have a population of over 320 million.

**Comment by ab77** [comment]
Feel free to re-build and test again, it is working again (at least for now).

-- ab1
