### ISSUE TITLE
is it possible to route specific domains to specific servers?

### ISSUE THREAD

**Issue by chovy** [ab77/netflix-proxy#58]
For example site1.com gets routed through UK server and site2.com gets routed through Canadian server...while the DNS server itself is on a US based server?

**Comment by ab77** [comment]
You'll have to have three DNS/proxy servers running all together in that case.

The US server (just needs DNS component unless you are also wanting to proxy US traffic) will respond with the IP of the U.K. server for site1.com requests and with the IP of the Canadian server for site2.com requests.

-- ab1

**Comment by chovy** [comment]
How do I set this up?

**Comment by ab77** [comment]
If you only watch from OSX, deploy netflix-proxy into each region and then:
http://hints.macworld.com/article.php?story=2004062902195410

Otherwise, deploy netflix-proxy into two regions you want to proxy and then setup dnsmasq on your US box to redirect to your two proxy instances, depending on site:
https://en.m.wikipedia.org/wiki/Dnsmasq

-- ab1

**Comment by chovy** [comment]
I'm curious why the first solution only works on OSX. I want to setup a DNS server on a vps that will route any specific requests through another VPS in the appropriate region.

This way I can use my DNS servers on any device where I want region unlocking.

**Comment by ab77** [comment]
Dnsmasq on your central VPS is probably the easiest in that case, something
like this:

/etc/dnsmasq.conf:

address=/site1.com/1.2.3.4
address=/site2.com/1.2.3.5

Where 1.2.3.4 is the IP of your Canadian proxy and 1.2.3.5 is the IP of
your US proxy. Look up the exact syntax for dnsmasq, because I am not sure
if the above is 100% correct.

Let me know how you go..

-- ab1

**Comment by chovy** [comment]
@ab77 -- do i need to use dnsmasq in conjunction with anything else or just standalone?

**Comment by ab77** [comment]
Hi, on you central VPS, you just need a basic DNS resolver, like dnsmasq.

On your proxies, you will need appropriate proxy services listening on
ports 80 and 443, e.g. sniproxy or haproxy.

-- ab1
