### ISSUE TITLE
All sites work except for the exceptions (Hulu, Showtime etc) on EC2

### ISSUE THREAD

**Issue by urbanappetite** [ab77/netflix-proxy#62]
Hi,

I setup an EC2 instance of Ubuntu, gave it inbound UDP DNS permissions to 0.0.0.0/0 and ran the following:

`curl -sSL https://get.docker.com/ | sh && sudo usermod -aG docker $(who am i | awk '{print $1}') && sudo git clone https://github.com/ab77/netflix-proxy /opt/netflix-proxy && cd /opt/netflix-proxy && sudo ./build.sh -c my.ip.add.ress`

No errors were given.

Websites generally work fine but the the exceptions like Hulu and iPlayer do not...

I updated the iptables to accept all incoming and outgoing connections (given that Amazon's firewall is doing this job) and that made Netflix start working but the other sites simply don't load.

Any ideas?

Thanks!

Luke

**Comment by ab77** [comment]
Hi there, are all the domains referenced in zones.override not working or just some?

If all of them don't work and the rest of the domains (not referenced) work, then the issue is probably with the sniproxy container not running or ports 80/443 not being forwarded to it.

Try to telnet from outside in to ports 80/443 on your public EC2 address (elastic IP) to see if you get a response.

You could in theory just drop iptables all together since you are using EC2 security group to do the same job.

-- ab1

**Comment by urbanappetite** [comment]
Thanks for your response. It's all of the domains referenced in the zonE override file.
I had already dropped the iptables rules.
The issue ended up being that I need to open port 80 and 443 on the EC2 firewall (On top of 53 UDP) - all's working now including Hulu

Thanks againLuke
    _____________________________

**Comment by ab77** [comment]
Good stuff!

Also good to know Hulu still works on AWS.

-- ab1

**Comment by meetshawn** [comment]
Are you sure? I just fired up an EC2 instance since Netflix stopped working on DigitalOcean. I'm still getting:
> You seem to be using an unblocker or proxy.

This is on US West Oregon.

**Comment by meetshawn** [comment]
Well it seems they're blocking certain EC2 IP ranges. I restarted my instance to get assigned a new IP but it didn't work since I guess it was in the same range as the original IP.

I assigned an elastic IP instead and now it's working. I should be noted though that EC2 IS being blocked now.
