### ISSUE TITLE
How can you add slave zone 

### ISSUE THREAD

**Issue by pakoris** [ab77/netflix-proxy#7]
Can you please let me know how to add a slave zone to the bind server on this configuration?

**Comment by ab77** [comment]
You probably don't want to do this, because it means opening up your DNS server to at least some additional DNS servers to do zone transfers, etc.

What are you actually trying to achieve by adding a slave zone?

If you really want to do it, there are lots of resources, including:
http://www.zytrax.com/books/dns/ch6/#slave
http://www.microhowto.info/howto/configure_bind_as_a_slave_dns_server.html
http://beginlinux.com/blog/2010/06/bind-create-slave-zone-files/

-- ab1

**Comment by ab77** [comment]
Just one more thing, editing `opt/netflix-proxy/docker-bind/named.conf`is no good to you, since this file gets baked into the bind docker image only during build and you are deploying pre-baked images from repository by default.

If you want to modify the live config, you will need to shell into your running docker image and edit the config there. To get into the docker container running as `bind`, use:
`docker exec -t -i bind bash`

Then use `vi`, etc.

If you are editing `opt/netflix-proxy/docker-bind/named.conf`, you will need to call `build.sh` as:
`./build.sh -b 1`

This will re-build your docker containers locally from source, rather than grabbing them from the Docker repository. This may fail, because the script isn't idempotent, so you'll have to clean-up existing docker images and containers first (i.e. `docker stop bind sniproxy; docker rm bind sniproxy; docker rmi bind sniproxy`)[n1].

Hope this helps..

-- ab1

[n1] check syntax..
